### ISSUE TITLE
At a loss to use this package on Sierra with XCode 8.2.1

### ISSUE THREAD

**Issue by biglambda** [danfran/cabal-macosx#2]
I'm using stack version 1.2.0 cabal 1.2.4 and ghc8.0.1
Initially I could not import Distribution.MacOSX into my Setup.hs until I moved a copy of Distribution into my toplevel project directory. Currently when I run stack build, I get a warning:

> Warning - Could not run the command "/Applications/XCode.app/Contents/Developer/Tools/Rez Carbon.r -o .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/crux-exe.app/Contents/MacOS/crux-exe". Please check your local `XCode` configuration.

If I try that command by itself in the terminal I get: 

> failed to find Carbon/Carbon.r
> ### /Applications/XCode.app/Contents/Developer/Tools/Rez - SysError 0 during open of "Carbon.r".
> Fatal Error!
> ### /Applications/XCode.app/Contents/Developer/Tools/Rez - Fatal Error, can't recover.
> Carbon.r: ### /Applications/XCode.app/Contents/Developer/Tools/Rez - Since errors occurred, .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/crux-exe.app/Contents/MacOS/crux-exe's resource fork was not written.

The resulting app bundle does not yet include the executable.

Here is my cabal file:
http://lpaste.net/923392959045435392
and my Setup.hs file:
http://lpaste.net/350585

If I search for Carbon.r it finds it here:

>/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Carbon.framework/Versions/A/Headers/Carbon.r

I've tried modifying the -F parameter to rez in at Internal.hs line 60 but so far to no avail.
Very excited to see my SDL2 application in Retina :) Any help is appreciated.

**Comment by danfran** [comment]
Have you tried to run first the command:

`xcode-select --install`

?

**Comment by biglambda** [comment]
Yes, I get:

>  xcode-select --install
>  xcode-select: note: install requested for command line developer tools

and it has no effect on the rez command.

**Comment by danfran** [comment]
Do you have your project in some repository so I can access to it, or a dummy project that reproduces the error? It would be easier for me to have a look into it.

**Comment by biglambda** [comment]
It's private and owned by my employer but I will try to create a dummy. Are you able to use it with a similar setup?

**Comment by danfran** [comment]
is this ok?

~$ stack --version
Version 1.3.2 x86_64 hpack-0.15.0
~$ cabal --version
cabal-install version 1.22.6.0
using version 1.22.4.0 of the Cabal library
~$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1.20161213
~$ xcodebuild -version
Xcode 8.2.1
Build version 8C1002

**Comment by biglambda** [comment]
Seems like it would be. Where is Carbon.r on your system?

**Comment by danfran** [comment]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Carbon.framework/Versions/A/Headers/Carbon.r
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Carbon.framework/Versions/A/Headers/Carbon.r
/System/Library/Frameworks/Carbon.framework/Versions/A/Headers/Carbon.r

**Comment by biglambda** [comment]
I think the might just be not having the right installation of Carbon Framework.
I get:
/.PKInstallSandboxManager-SystemSoftware/5231E5AD-C4EF-41C8-BF56-BB6E18303077.sandbox/Root/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Carbon.framework/Versions/A/Headers/Carbon.r
/.PKInstallSandboxManager-SystemSoftware/5231E5AD-C4EF-41C8-BF56-BB6E18303077.sandbox/Root/System/Library/Frameworks/Carbon.framework/Versions/A/Headers/Carbon.r
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Carbon.framework/Versions/A/Headers/Carbon.r

**Comment by tgass** [comment]
I ran into the described problem while building the wxHello example on macos 10.14.6, XCode 11.10 and stack 2.3.1. Happy for pointers!

**Comment by tgass** [comment]
All good. There's still an older version of cabal-macosx mentionend in the README.
